---
# tasks file for ansible-git
- git_config:
     name: user.name
     scope: global
     value: Enda Ridge

- git_config:
     name: user.email
     scope: global
     value: "nope@nope.co.uk"


- git_config:
    name: core.editor
    scope: global
    value: nano
