---
# run locally here, yadda yadda yadda

- hosts: local
  any_errors_fatal: true
  # ensure Python2 is installed for ansible to work correctly
  # switch off gather_facts temporarily as that also fails without
  # Python2 present
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      become: yes
      raw: apt-get -y install python #python-pip
      when: ansible_os_family == 'Debian'


    - name: Ensure brew is installed on Mac
      include_role:
        name: ansible-role-homebrew
      when: ansible_os_family == 'Darwin'


  gather_facts: yes

  vars:
    pycharm_edition: community
    pycharm_version: 2018.3.4
    # pycharm_install_prefix: ansible_env.HOME

  connection: local
  #become: yes

  tasks:
    - name: Upgrade apt cache on Linux
      become: yes
      apt:
        upgrade: yes
        cache_valid_time: 604800 #update cache if been more than one day in secs
      when: ansible_os_family == 'Debian'
      tags: upgrade

    - name: Print ansible_os_family
      debug: var=ansible_os_family


    - name: Install Atom if on Linux
      include_role:
        name: ansible-role-atom
      when: ansible_os_family == 'Debian'

    - name: Install PyCharm on Linux
      include_role:
        name: ansible-role-pycharm
      vars:
          pycharm_version: 2018.3.5
          pycharm_edition: community
      when: ansible_os_family == 'Debian'


    - name: Install OpenJDK on MacOS
      become: yes
      homebrew_cask:
        name: adoptopenjdk8
        state: present
      when: ansible_os_family == 'Darwin'
      tags: java


    - name: Install awscli
      pip:
        name: awscli
        #version: "{{ awscli_version }}"
        extra_args: --user
      tags: awscli

    - name: Ensure ~/.aws directory exists
      file: >
        path="{{ ansible_env.HOME }}/.aws"
        state=directory
      tags: awscli

    # - name: Install ~/.aws/credentials
    #   copy:
    #     src: credentials
    #     dest: "{{ home_directory }}/.aws/credentials"
    #     mode: 0644



  roles:
    - role: ansible-data-science-cli
      tags: data-science-cli

    - role: ansible-git
      tags: git

    # - role: ansible-postgresql
    #   become: yes
    #   vars:
    #     postgresql_users:
    #       - name: enda
    #       - name: postgres
    #     postgresql_databases:
    #       - name: example_db
    #     postgresql_hba_entries:
    #       - { type: all, database: all, user: all, auth_method: trust }
    #   tags: postgresql

    - role: avanov.pyenv
      vars:
        pyenv_path: "{{ ansible_env.HOME }}/.pyenv"
        #pyenv_owner: "{{ instance_owner }}"
        pyenv_global: "2.7.16"
        pyenv_update_git_install: no
        pyenv_enable_autocompletion: yes
        pyenv_python_versions:
         - "3.7.2"
         - "2.7.16"
        pyenv_virtualenvs:
         - venv_name: "latest_v3"
           py_version: "3.7.2"

         - venv_name: "latest_v2"
           py_version: "2.7.16"
      tags: pyenv
