---
# run locally here, yadda yadda yadda

- hosts: local
  vars:
    gather_facts: true
    pycharm_edition: community
    pycharm_version: 2018.3.4
    # pycharm_install_prefix: ansible_env.HOME

  connection: local
  become: yes
  tasks:
    - name: Print ansible_os_family
      debug: var=ansible_os_family

  roles:
    - ansible-data-science-cli
    - ansible-chrome
    - ansible-git
    - ansible-role-atom
    - ansible-role-docker
    - role: role-atom-packages
      users:
        - username: "{{ ansible_user_id }}"
          atom_packages:
            - minimap
            - linter
            - atom-beautify
            - file-icons
            - teletype
            - highlight-selected
            - tablr     # view CSV files as a table
            - language-markdown     # markdown packages
            - markdown-writer
            - markdown-preview
    - role: ansible-role-pycharm
      pycharm_version: 2018.3.5
      pycharm_edition: community
      # pycharm_plugins:
          # bash support 1.7.4
          # - 53225
