---
# run locally here, yadda yadda yadda

- hosts: local

  # ensure Python2 is installed for ansible to work correctly
  # switch off gather_facts temporarily as that also fails without
  # Python2 present
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  gather_facts: yes

  vars:
    pycharm_edition: community
    pycharm_version: 2018.3.4
    # pycharm_install_prefix: ansible_env.HOME

  connection: local
  become: yes

  tasks:
    - name: Print ansible_os_family
      debug: var=ansible_os_family

    - name: Install Atom if on Linux
      include_role:
        name: ansible-role-atom
      when: ansible_os_family == 'Debian'

    - name: Install PyCharm on Linux
      include_role:
        name: ansible-role-pycharm
      vars:
          pycharm_version: 2018.3.5
          pycharm_edition: community
      when: ansible_os_family == 'Debian'

    - name: Install Chrome on linux
      include_role:
          name: ansible-role-chrome-linux
      when: ansible_os_family == 'Debian'

  roles:
    - ansible-data-science-cli
