# Install a role at a specific tag from GitHub
# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
- name: ansible-role-atom
  src: https://github.com/gantsign/ansible-role-atom
  version: 2.0.1

- name: role-atom-packages
  src: https://github.com/gantsign/ansible-role-atom-packages
  version: 1.2.0

