# Install a role at a specific tag from GitHub
# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
- name: ansible-role-atom
  src: https://github.com/gantsign/ansible-role-atom
  version: 2.0.1

- name: ansible-role-atom-macos
  src: https://github.com/christopherdwhite/ansible-role-atom.git

- name: role-atom-packages
  src: https://github.com/gantsign/ansible-role-atom-packages
  version: 1.2.0

- name: ansible-role-chrome-linux
  src: https://github.com/cmprescott/ansible-role-chrome
  version: 0.2.4

# Install and configure pycharm
# https://github.com/henriklynggaard/ansible-role-pycharm
- name: ansible-role-pycharm
  src: https://github.com/henriklynggaard/ansible-role-pycharm
  version: v1.1

- name: ANXS.postgresql
  src: https://github.com/ANXS/postgresql/
  version: 1.11.1

- name: ansible-role-docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.2
