# Install a role at a specific tag from GitHub
# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
- name: ansible-role-atom
  src: https://github.com/gantsign/ansible-role-atom
  version: 2.0.1

- name: role-atom-packages
  src: https://github.com/gantsign/ansible-role-atom-packages
  version: 1.2.0

# Install and configure pycharm
# https://github.com/henriklynggaard/ansible-role-pycharm
- name: ansible-role-pycharm
  src: https://github.com/henriklynggaard/ansible-role-pycharm
  version: v1.1

- name: ansible-role-postgresql
  src: https://github.com/geerlingguy/ansible-role-postgresql
  version: 1.4.5

- name: ansible-docker-postgres
  src: https://github.com/levonet/ansible-docker-postgres
  version: v0.1.0

- name: ansible-role-docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.2
