# Install a role at a specific tag from GitHub
# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles


#- name: ansible-role-homebrew
#  src: https://github.com/geerlingguy/ansible-role-homebrew

- name: ansible-role-atom
  src: https://github.com/gantsign/ansible-role-atom.git
  version: 2.1.0

- name: ansible-role-atom-macos
  src: https://github.com/christopherdwhite/ansible-role-atom.git

- name: role-atom-packages
  src: https://github.com/gantsign/ansible-role-atom-packages
  version: 1.2.0

- name: ansible-role-chrome-linux
  src: https://github.com/cmprescott/ansible-role-chrome
  version: 0.2.4

- name: markosamuli.pyenv
  src: https://github.com/markosamuli/ansible-pyenv
  version: v4.0.2

# Install and configure pycharm
# https://github.com/henriklynggaard/ansible-role-pycharm
# - name: ansible-role-pycharm
#   src: https://github.com/henriklynggaard/ansible-role-pycharm
  #version: v1.1
- name: ansible-docker
  src: https://github.com/nickjj/ansible-docker
  version: v2.0.0

  ########################
  # Languages
- name: diodonfrost.java
  src: https://github.com/diodonfrost/ansible-role-java
  version: 1.12.0

- name: hnakamur.atom-packages
  src: https://github.com/hnakamur/ansible-role-atom-packages

- name: igor_mukhin.bash_aliases
  src: https://github.com/carlba/ansible-role-bash_aliases
