# tasks file for chrome
---
- include: repository.yml
  tags:
    - configuration
    - chrome
    - chrome-repository

- include: install.yml
  tags:
    - configuration
    - chrome
    - chrome-install
