# tasks file for chrome
---
- name: add public key
  apt_key:
    id: A040830F7FAC5991
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  tags:
    - chrome-repository-public-key

- name: add chrome repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ chrome_repositories }}"
  tags:
    - chrome-repository-add
