- name: Install postgres on Linux
  include_role:
      name: geerlingguy.postgresql
  when: ansible_os_family == 'Debian'
  tags:
      - postgresql

- name: Install pgadmin4
  apt:
    name: pgadmin4
    state: present
  tags:
      - postgresql
