---
# tasks file for ansible-postgresql
  # pre_tasks:
  #
  #   - name: Ensure postgres directory exists
  #     become: yes
  #     file: >
  #       path="/var/lib/postgresql/10/main"
  #       state=directory
  #     tags: postgresql

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: Debian.yml
  when: ansible_os_family == 'Debian'
