---
# Command line tools
# Based partly on
# https://www.datascienceworkshops.com/blog/seven-command-line-tools-for-data-science/

# https://stackoverflow.com/a/47227017
- name: ensure node is installed for use by Ansible
  become: yes
  apt:
    name: ["{{ item }}"]
    state: present
  with_items:
    - nodejs
    - npm

- name: Install Linux command line utilites on Debian
  become: yes
  apt:
    name: ["{{ item }}"]
    state: present
  with_items:
    - acl
    - unattended-upgrades
    - policykit-1
    - ntp
    - curl
    - gawk
    - vim
    - ack-grep
    - grep
    - git
    - unzip
    - htop
    - tmux
    - tree
    - mc
    - bash-completion
    - sed
    - htop
    - rename
    - net-tools
    - watch
    - wget
    #- cut
    #- sort
    #- wc
    #- uniq

- name: Install jq command line utility on Debian
  become: yes
  apt:
    name: jq
    state: present

- name: Install subsample python package
  pip:
    name: subsample
  tags: subsample

- name: Install csvkit for CSV file manipulation
  become: yes
  apt:
    name: csvkit
    state: present
  tags: csvkit
#
- name: Install "json2csv" command line tool for converting json into csv
  become: yes
  npm:
    name: json2csv
    global: yes
  tags: json2csv

- name: Install "xml2json" command line tool for XML conversion
  become: yes
  npm:
    name: xml2json-command
    global: yes
  tags: xml2json

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400 #update cache if been more than one day in secs
