---
# tasks file for ansible-data-science-cli
# based on http://edunham.net/2015/09/10/ansible_conditional_role_dependencies.html
- include: osx.yaml
  when: ansible_os_family == 'Darwin'

- include: Debian.yaml
  when: ansible_os_family == 'Debian'

