  - name: Install command line utilites on MacOS
    homebrew:
      name: ["{{ item }}"]
      state: present
    with_items:
      - ntp
      - wget
      - curl
      - vim
      - ack   #  called ack-grep on linux
      - git
      - unzip
      - htop
      - tmux
      - tree
      - mc
      - bash-completion
      - htop
      - rename


  - name: Install meld on MacOS
    homebrew_cask:
      name: meld
      state: present

  - name: Install jq JSON command line processor on MacOS
    homebrew:
      name: jq
      state: present
