  - name: Install basics
    homebrew:
        name: "{{ packages }}"
    become: no
    vars:
        packages:
        # - acl   #removed from macos
        # - unattended-upgrades   #removed from macos
        # - policykit-1   #removed from macos
        - ntp
        - wget
        - curl
        - vim
        - ack   #  called ack-grep on linux
        - git
        - unzip
        - htop
        - tmux
        - tree
        - mc
        - bash-completion
        - htop
        - rename
